import type { NextPage } from "next"
import Head from "next/head"
import { Button, Stack, Box } from "@mui/material"

const Home: NextPage = () => {
  return (
    <>
      <Box px={2}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Stack spacing={1} mt={2}>
          <Button variant="contained">Hello</Button>
          <Button variant="outlined">Hello</Button>
        </Stack>

        <div className="test" />

        <div className="daoalert-widget" data-symbol="daoalert-widget"></div>
      </Box>
    </>
  )
}

export default Home
